version: '3'

services:
  web:
    image: registry.muskegg.com:5000/webresume:latest 
    build:
      context: ./app
      network: host
      dockerfile: Dockerfile.prod
    command: gunicorn raph.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    image: registry.muskegg.com:5000/webresume-nginx:latest
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static

volumes:
  postgres_data:
  static_volume:
